Repository gmarino2048/AGD_Project, pull requests merged in 2018-12, with the labels that each got.

#399 Fixed the button
  Master Project/Assets/Scenes/NameEntry/NameEntry.unity
Labels: Art

#400 Dialogue marino
  Master Project/Assets/Scenes/Dialogue/Assets/UX UI/Pizarro-Ruiz_DialogueCounter_2.png
  Master Project/Assets/Scenes/Dialogue/Assets/UX UI/Pizarro-Ruiz_DialogueCounter_2.png.meta
  Master Project/Assets/Scenes/Dialogue/DialogueScene.unity
Labels: Art, Programming

#391 Its Her
  Art/Backgrounds/Monster Splash Art/Phillips_REDACTED_DateArt_2.png
  Art/Backgrounds/Monster Splash Art/Pizarro-Ruiz_NessieDate_1.png
Labels: Art

#409 Made the buttons work
  Master Project/Assets/Scenes/Chopping/Chopping.unity
  Master Project/Assets/Scenes/Dialogue/DialogueScene.unity
  Master Project/Assets/Scenes/Grill/Grill.unity
  Master Project/Assets/Scenes/Ingredients/IngredientsScene.unity
  Master Project/Assets/Scenes/Microwave/Microwaving.unity
  Master Project/Assets/Scenes/Shaking/Shaking.unity
  Master Project/Assets/Scenes/Stirring/Stirring.unity
Labels: Programming

#411 Final scene3 goldberg
  Master Project/Assets/Scenes/FinalChoice/FinalChoice.unity
  Master Project/Assets/Scenes/FinalChoice/Prefabs/MonsterChoiceButton.prefab
  Master Project/Assets/Scenes/FinalChoice/Scripts/FinalChoiceSceneManager.cs
Labels: Art, Programming

#414 Minigames use volume properly now
  Master Project/Assets/Scenes/Chopping/Scripts/SFXController.cs
  Master Project/Assets/Scenes/Grill/Scripts/SFXController.cs
  Master Project/Assets/Scenes/Microwave/Scripts/SFXController.cs
  Master Project/Assets/Scenes/Shaking/Scripts/SFXManager.cs
  Master Project/Assets/Scenes/Stirring/Scripts/SFXManager.cs
Labels: Programming

#413 added sounds
  Master Project/Assets/Scenes/FinalChoice/FinalChoice.unity
  Master Project/Assets/Scenes/FinalChoice/Scripts/FinalChoiceSceneManager.cs
  Master Project/Assets/Scenes/FinalChoice/Sound.meta
  Master Project/Assets/Scenes/FinalChoice/Sound/Getting to Know You.mp3
  Master Project/Assets/Scenes/FinalChoice/Sound/Getting to Know You.mp3.meta
  Master Project/Assets/Scenes/FinalChoice/Sound/Monster Date Aquired.mp3
  Master Project/Assets/Scenes/FinalChoice/Sound/Monster Date Aquired.mp3.meta
  Master Project/Assets/Scenes/FinalChoice/Sound/Phone Dialing.mp3
  Master Project/Assets/Scenes/FinalChoice/Sound/Phone Dialing.mp3.meta
  Master Project/Assets/Scenes/FinalChoice/Sound/Telephone Ringing.mp3
  Master Project/Assets/Scenes/FinalChoice/Sound/Telephone Ringing.mp3.meta
  Master Project/Assets/Scripts/MusicManager.cs
Labels: Art, Programming, Sound

#410 moved button
  Master Project/Assets/Scenes/GameOver/Game OVer.unity
Labels: Art, Programming

#422 Added sfx to main menu and fixed eggs sound for stirring
  Master Project/Assets/Scenes/Main Menu/Audio.meta
  Master Project/Assets/Scenes/Main Menu/Audio/Menu Navigation.mp3
  Master Project/Assets/Scenes/Main Menu/Audio/Menu Navigation.mp3.meta
  Master Project/Assets/Scenes/Main Menu/Audio/Menu Selection.mp3
  Master Project/Assets/Scenes/Main Menu/Audio/Menu Selection.mp3.meta
  Master Project/Assets/Scenes/Main Menu/Main Menu.unity
  Master Project/Assets/Scenes/Stirring/Assets/Audio/Egg Beater.mp3
  Master Project/Assets/Scenes/Stirring/Assets/Audio/Egg Beating.mp3
  Master Project/Assets/Scenes/Stirring/Assets/Audio/Egg Beating.mp3.meta
  Master Project/Assets/Scenes/Stirring/Assets/Tool.meta
  Master Project/Assets/Scenes/Stirring/Stirring.unity
Labels: Programming

#423 Updated XML values for combat'
  Master Project/Assets/StreamingAssets/Data/Monsters.xml
Labels: Programming

#424 Ingredients fix
  Master Project/Assets/Scenes/Ingredients/IngredientsScene.unity
  Master Project/Assets/Scenes/Ingredients/Scripts/IngredientController.cs
  Master Project/Assets/Scenes/Ingredients/Scripts/IngredientManager.cs
  Master Project/Assets/Scenes/Ingredients/Scripts/SFXController.cs
Labels: Programming

#425 Remove the warnings
  Master Project/Assets/Scenes/Dialogue/Scripts/AssetManager.cs
  Master Project/Assets/Scenes/Grill/Scripts/PlacementHelper.cs
  Master Project/Assets/Scenes/Ingredients/Scripts/IngredientManager.cs
  Master Project/Assets/Scenes/Monologue/Scripts/MonologueSceneManager.cs
  Master Project/Assets/Scenes/NameEntry/Scripts/InputTextScript.cs
  Master Project/Assets/Scenes/Shaking/Scripts/ScorekeeperBehavior.cs
Labels: Programming

#427 Fixed some monologue lines
  Master Project/Assets/StreamingAssets/Data/GameNarrative.xml
Labels: Programming

#428 DestroyImmediate
  Master Project/Assets/Scripts/PersistentObject.cs
Labels: Programming

#429 More fixes
  Master Project/Assets/Scenes/Ingredients/IngredientsScene.unity
  Master Project/Assets/Scenes/Ingredients/Scripts/SFXController.cs
  Master Project/Assets/Scenes/Main Menu/Sprites/Instructions.meta
  Master Project/Assets/Scenes/NameEntry/NameEntry.unity
  Master Project/Assets/Scenes/Stirring/Assets/Tool.meta
  Master Project/Assets/Scripts/PauseMenu/OpenPauseButton.cs
  Master Project/Assets/Scripts/PersistentObject.cs
Labels: Programming

#430 MORE
  Master Project/Assets/Scenes/Chopping/Scripts/SFXController.cs
  Master Project/Assets/Scenes/Combat/Scripts/GameFlowController.cs
  Master Project/Assets/Scenes/Combat/Scripts/Sounds/MusicController.cs
  Master Project/Assets/Scenes/Combat/Scripts/Sounds/SFXController.cs
  Master Project/Assets/Scenes/Grill/Scripts/SFXController.cs
  Master Project/Assets/Scenes/Ingredients/Scripts/SFXController.cs
  Master Project/Assets/Scenes/Microwave/Scripts/SFXController.cs
  Master Project/Assets/Scenes/Shaking/Scripts/SFXManager.cs
  Master Project/Assets/Scenes/Stirring/Scripts/SFXManager.cs
Labels: Programming

#435 Glitter Glitter Sparkle Sparkle Welcome to Claire's
  Art/UXUI/PNG/Pizarro-Ruiz_SparkleSparkle_1.png
Labels: Art
